# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby_dep/all/ruby_dep.rbi
#
# ruby_dep-1.5.0

module RubyDep
end
class RubyDep::Travis
  def failable(yaml); end
  def lowest_minor_without_skipping(grouped_by_minor); end
  def lowest_supported(versions); end
  def supported_versions(yaml); end
  def version_constraint(filename = nil); end
  def versions_for_latest_major(versions); end
end
class RubyDep::Travis::RubyVersion
  def initialize(travis_version_string); end
  def jruby_version(version); end
  def segments; end
  def version_for(travis_version_string); end
end
class RubyDep::Travis::RubyVersion::Error < RuntimeError
end
class RubyDep::Travis::RubyVersion::Error::Unrecognized < RubyDep::Travis::RubyVersion::Error
  def initialize(invalid_version_string); end
  def message; end
end
class RubyDep::Travis::RubyVersion::Error::Unrecognized::JRubyVersion < RubyDep::Travis::RubyVersion::Error::Unrecognized
  def message; end
end
