language: ruby
script: bundle exec rails test
install: bundle install
before_install:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres -p 5432 -h 127.0.0.1
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
rvm:
  - 2.6.3
