language: ruby
before_install:
  - elasticsearch-plugin install analysis-kuromoji
install: bundle install
before_install:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test_private_rails_test;' -U postgres
addons:
  postgresql: "10"
services:
  - elasticsearch
before_script:
  - sleep 10
rvm:
  - 2.6.3
script: bundle exec rails test
script: bundle exec srb tc
